language: ruby
rvm:
  - 2.1
sudo: false
cache: bundler
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --allow-hash-href --file-ignore "/.*/_site/assets/.*/"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
