language: ruby # don't install any environment
rvm:
- 2.1
sudo: required
env:
  global:
  - ENCRYPTION_LABEL: "encrypted_6e80fb8f9d7f"
  - COMMIT_AUTHOR_EMAIL: "idealab@asu.edu"
  - SOURCE_BRANCH: "stable"
  - TARGET_BRANCH: "master"

install: 
  - gem install jekyll jekyll-scholar jekyll-paginate
  
before_script:
  - chmod +rx deploy.sh
  - chmod +rx compile.sh

script: bash ./deploy.sh

