organization_name: IDEAlab
title: IDEAlab -- Integrating Design, Engineering, and Analysis
email: danaukes@asu.edu
# description: > # this means to ignore newlines until "baseurl:"
  # Integrating Design, Engineering, and Analysis
url: "http://idealab.asu.edu" # the base hostname & protocol for your site
#url: "http://www.public.asu.edu" # the base hostname & protocol for your site
# url: "http://idealabasu.com" # the base hostname & protocol for your site
#url: "localhost:4000" # the base hostname & protocol for your site

#base_path: "/~daukes"
base_path: ""

address:
  - Technology Center, Room 180
  - 6075 S. Innovation Way West
  - Mesa, AZ 85212

phone: 480-727-1573

include:
  - .nojekyll

exclude:
  - compile.sh
  - deploy.sh
  - vendor
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - .yarnrc
  - .gitignore
  - docker-compose.yml
  - package.json

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      image:
        feature: /assets/images/image1.jpg
      show_title: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post_custom"
#      show_title: true


kramdown:
  input: GFM
  auto_ids: true
highlighter: rouge
 
twitter_id: IDEAlab

menu:
  - name: Research
    links: 
    - name: Research Projects & Platforms
      link: projects
    - name: Publications
      link: publications
    - name: Posters
      link: posters
    - name: Kaiteki Project
      link: kaiteki
  - name: Videos
    link: videos
  - name: Lab Info
    links:
    - name: People
      link: people
    - name: Calendar
      link: calendar
    - name: Contact & Location
      link: contact-and-location
    - name: Equipment & Facilities
      link: equipment
    - name: Press
      link: press
    - name: News
      link: news
    - name: Research Opportunities
      link: research-opportunities
    - name: Conferences
      link: conferences
    - name: Download
      link: download
  - name: Teaching
    link: teaching

tags: a,b,c,d


scholar:
  style: assets/ieee-dan-mod.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: assets/bibliographies
  bibliography: mypapers.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings: true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: details.html
  details_link:   (details)

  query: "@*"

#gems: [jekyll-paginate]
plugins: [jekyll-paginate, jekyll/scholar]

form_redirect: /submitted
permalink: ordinal
markdown: kramdown
show_drafts: false
