defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"      

base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: pygments

organization_name: IDEAlab
title: IDEAlab -- Integrating Design, Engineering, and Analysis

menu:
  - name: Publications
    link: publications
  - name: Research
    link: research
    
tags: a,b,c,d


scholar:
  style: assets/ieee.csl
  locale: en
  sort_by: year
  order: descending
  source: assets
  bibliography: bibliography.bib
  bibliography_template: bibtemplate
  replace_strings: true
  join_strings: true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

gems: [jekyll-paginate]