organization_name: IDEAlab
title: IDEAlab -- Integrating Design, Engineering, and Analysis
email: idealab@asu.edu
# description: > # this means to ignore newlines until "baseurl:"
  # Integrating Design, Engineering, and Analysis
url: "http://idealab.asu.edu" # the base hostname & protocol for your site
#url: "http://www.public.asu.edu" # the base hostname & protocol for your site
# url: "http://idealabasu.com" # the base hostname & protocol for your site
#url: "localhost:4000" # the base hostname & protocol for your site

#base_path: "/~daukes"
base_path: ""

address:
  - Technology Center, Room 180
  - 6075 S. Innovation Way West
  - Mesa, AZ 85212

phone: 480-727-1573

include:
  - .nojekyll

exclude:
  - compile.sh
  - deploy.sh

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      image:
        feature: image1.jpg
      show_title: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post_custom"
#      show_title: true


kramdown:
  input: GFM
  auto_ids: true
highlighter: pygments


menu:
  - name: Research
    link: research
  - name: People
    link: people
  - name: Publications
    link: publications
  - name: Teaching
    link: teaching
  - name: Videos
    link: videos
  - name: Visit
    link: visit
  - name: Contact
    link: contact
  - name: Jobs
    link: jobs

tags: a,b,c,d


scholar:
  style: assets/ieee-dan-mod.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: assets/bibliographies
  bibliography: papers_journal.bib
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings: true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
#  details_layout: bib-details.html
  details_layout: none.html
  details_link:   more...

  query: "@*"

#gems: [jekyll-paginate]
gems: [jekyll-paginate, jekyll/scholar]

form_redirect: /submitted
permalink: ordinal
markdown: kramdown
show_drafts: false
