baseURL: "https://idealab.asu.edu"
languageCode: "en-us"
title: "IDEAlab"
theme:
 - hugo-cite

params:
  github_repo: "https://github.com/idealabasu/idealabasu.github.io"
  github_edit_branch: main
  organization_name: IDEAlab
  home_path: ""
  author: Daniel M. Aukes
  description: IDEAlab Homepage
  email: danaukes@asu.edu

ignorefiles:
  - ignore/*
  - content/teaching/*

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokailight
    noClasses: true

ignoreErrors:
- "error-remote-getjson"

enableInlineShortcodes: true
